eosnetworkfoundation/mandel

.gitignore, README.md, libraries/CMakeLists.txt, libraries/state_history/.clang-format, libraries/state_history/CMakeLists.txt, libraries/state_history/abi.cpp, libraries/state_history/compression.cpp, libraries/state_history/create_deltas.cpp, libraries/state_history/include/eosio/state_history/compression.hpp, libraries/state_history/include/eosio/state_history/create_deltas.hpp, libraries/state_history/include/eosio/state_history/log.hpp, libraries/state_history/include/eosio/state_history/serialization.hpp, libraries/state_history/include/eosio/state_history/trace_converter.hpp, libraries/state_history/include/eosio/state_history/types.hpp, libraries/state_history/trace_converter.cpp, package.json, plugins/state_history_plugin/CMakeLists.txt, plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_plugin.hpp, plugins/state_history_plugin/state_history_plugin.cpp, tests/CMakeLists.txt, tests/ship_client.js, tests/ship_test.py, tests/testUtils.py
Backport ship from 29233b8
* Kept ship format at 2.0.x, except `get_status_result_v0` has the additional `chain_id` field
* Kept 2.0.x's fix to shut down on ship write error
* Kept 2.0.x's block_start handling
=> backport 29233b8 ship

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/include/eosio/chain/account_object.hpp, libraries/chain/include/eosio/chain/authority.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/generated_transaction_object.hpp, libraries/chain/include/eosio/chain/reversible_block_object.hpp, libraries/chain/include/eosio/chain/types.hpp, libraries/state_history/create_deltas.cpp, libraries/state_history/include/eosio/state_history/serialization.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/history_plugin/history_plugin.cpp, programs/eosio-blocklog/main.cpp, programs/nodeos/main.cpp, tests/Cluster.py, tests/testUtils.py, tests/validate-dirty-db.py
Backport chainbase from 2.1.
https://github.com/EOSIO/eos/pull/8181
https://github.com/EOSIO/eos/pull/9577
=> backport 2.1 chainbase

CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in
Backport tester cmake changes from 2.1. This fixes building mandel-contracts.
=> backport 2.1 tester cmake

libraries/state_history/abi.cpp, libraries/state_history/include/eosio/state_history/serialization.hpp
2.1's ship was missing wasm_config.
=> Fix #10: ship support for wasm_config

libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/eos-vm-oc.hpp, libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp
We're incompatible with 2.1 due to a different host function table (see intrisic_mapping.hpp).
=> Increment codegen_version 

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/producer_plugin/producer_plugin.cpp
- Respect the `cpu-effort-percent` while removing expired transactions from deduplication list.
=> Limit input transaction dedup time

plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp, plugins/producer_plugin/producer_plugin.cpp, plugins/producer_plugin/test/test_subjective_billing.cpp
- Additional subjective cpu logging
- https://github.com/EOSIO/eos/pull/11074
=> Add additional subjective cpu logging

plugins/net_plugin/net_plugin.cpp
- Add option `p2p-dedup-cache-expire-time-sec` for configurating the transaction deduplication cache expiration time.
- Simplify transaction deduplication cache handling to just be a configurable expire time.
- The dedup cache, `local_txns`, is simply an optimization in net_plugin to avoid tripping duplication transaction exception in `controller`.
- The current implementation (before this PR) prevents clients from re-trying transactions as the `net_plugin` would not accept the transaction again until it expired or it appeared in a block.
=> net_plugin transaction dedup cache handling

plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp, plugins/producer_plugin/producer_plugin.cpp
Do not apply the 3-strike rule to disable-subjective-account-billing accounts.
=> ENFS-43: Add Configured Whitelist to Ignore Number of Failures

plugins/chain_plugin/trx_retry_db.cpp
- Take advantage of tracked_storage erase that takes an iterator in `trx_retry_db`
- Updates to latest `fc` `main` which includes `tracked_storage::erase` that takes an iterator and `mock_time_traits::set_now` that takes an `fc::time_point`.
=> Take advantage of tracked_storage erase that takes an iterator

.github/workflows/ubuntu-2004.yml, tests/CMakeLists.txt, tests/Cluster.py, tests/Node.py, tests/TestHelper.py, tests/nodeos_forked_chain_test.py, tests/nodeos_high_transaction_test.py, tests/nodeos_under_min_avail_ram.py
- Back port https://github.com/EOSIO/eos/pull/8222 as this will be the basis of transaction retry integration test
=> Many Transaction Long Running Test

tests/cli_test.py
Best I can tell, the cli_test does not need keosd to test what it is trying to test. So add --no-auto-keosd on the cleos calls to prevent keosd from starting. Otherwise, a keosd using the default wallet path is left running after the tests are completed.
This leftover keosd is probably quite benign in this case, though imo it's nice to keep the ctest -LE _tests variety of tests (i.e. "parallelizable tests") leave behind no side effects.
Ports EOSIO/eos#10134
=> add --no-auto-keosd to cli_test

plugins/trace_api_plugin/test/test_compressed_file.cpp, plugins/trace_api_plugin/test/test_configuration_utils.cpp, programs/eosio-launcher/main.cpp
Adds some includes needed to build with boost 1.79 beta. 
The missing includes are solely related to fstream & boost::filesystem::fstream. The boost filesystem docs (even as far back as 1.66) are clear that `#include <boost/filesystem.hpp>` does not include file stream support. Internal changes to boost filesystem in 1.79 (namely removal of string_file) means that `boost/filesystem/fstream.hpp` no longer get implicitly included via `boost/filesystem.hpp`, so we need to be explicit about this.
Needs submodule PRs eosnetworkfoundation/mandel-chainbase#2 & eosnetworkfoundation/mandel-fc#15
Ports over EOSIO/eos#11079
=> add some needed includes to build with boost 1.79 beta

.github/workflows/ubuntu-2004.yml
- Wasm Spec Tests are the longest running tests. Split into two jobs so they can run in parallel.
=> Split wasm spec tests into two jobs so they run quicker.

CMakeLists.txt, programs/cleos/CMakeLists.txt, programs/cleos/localize.hpp, programs/cleos/main.cpp, scripts/eosio_build.sh, scripts/generate_bottle.sh
gettext is only used for cleos localization support. But, cleos has not had any effort to translate it thus far. Remove this unused dependency for now as it's an LGPL dep and may cause some grief depending on future platform support. When we get back around to localizing cleos we can reevaluate this need; it's possible something like boost::locale would be a better fit.
Port of EOSIO/eos#8118 & EOSIO/eos#10326
=> remove gettext/libintl dependency

.github/workflows/ubuntu-2004.yml, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/trx_retry_db.cpp, tests/CMakeLists.txt, tests/Node.py, tests/nodeos_retry_transaction_test.py, tests/testUtils.py
- Includes a fix for transaction retry expiration comparison.
- New integration test for transaction retry feature
```
#
```
=> Add new transaction retry integration test

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/transaction_context.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/test/test_trx_finality_status_processing.cpp, tests/nodeos_retry_transaction_test.py
- Remove requirement for `disable-api-persisted-trx` to be `true` for transaction retry feature, as it is not required. Transaction retry will work with it enabled or disabled.
- Fix some compiler warnings.
=> Remove requirement for disable-api-persisted-trx to be true

libraries/chain/controller.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/CMakeLists.txt, tests/Node.py, tests/compute_transaction_test.py
This PR turns off subjective billing for read-only transactions.
*** Warning ***
An effect of this change is that compute_transaction becomes a potential DOS attack vector for any node that has enabled the compute_transaction end point.  Any exposed node should implement some form of throttling to prevent this sort of attack.
=> Don't apply subjective billing to read-only transactions

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, programs/cleos/main.cpp
- Changed `compute_transaction` & `send_transaction2` to generate 400 http code on invalid input to match newer scheme for http errors. See https://github.com/EOSIO/eos/pull/9033 which will likely be backported to Mandel. For now this only applies the #9033 approach to `compute_transaction` & `send_transaction2`.
- Renamed `return_failure_traces` to `return_failure_trace`.
- Changed to default of `return_failure_trace` to `true`
-  Currently ignored: feature not implemented yet.
=> compute_transaction & send_transaction2 cleanup

CMakeLists.txt, CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in, README.md, libraries/chain/include/eosio/chain/types.hpp
Replace the old libsecp256k1 fork with upstream. The initial motivation for this change was performance: upstream libsecp256k1 can make use of now expired patented optimizations that significantly reduce the amount of time to perform key recovery.
There are two other significant benefits though. The previous fork in use was many many years old and some users have voiced concern about usage of such stale forks (EOSIO/eos#8984). It's certainly desirable to get back on track with the upstream repository. Plus, this latest version of libsecp256k1 no longer needs GMP to perform at optimal speed -- they've even completely removed that code path from the library. GMP is an LGPL library and removing it as a dependency opens up the possibility for future positive changes to binary releases. …
=> replace old libsecp256k1 fork with upstream & remove GMP dependency

tests/nodeos_forked_chain_test.py, tests/nodeos_short_fork_take_over_test.py
This ports over EOSIO/eos#10356 & EOSIO/eos#10879. The original description from @dimas1185:
>This PR fixes 2 flaky parts in nodeos_forked_chain_lr_test and nodeos_short_fork_take_over_lr_test:
>
>1. if node_02 transfer extra block on shutdown, i.e. it was supposed to be killed on block x, but during shutdown it have got x+1 and populated it. For this to be handled correctly, line 434 was removed.
>Example of such failure: https://buildkite.com/EOSIO/eosio/builds/30786#854e0f8f-16e4-4385-81c6-c0d935b1c052
>2. need a bit more time to resolve the fork. See line 510. Example of failure: https://buildkite.com/EOSIO/eosio/builds/30805#d6a12c86-b3a9-4efc-b983-2baa24a03e1a
>3. Same code changes were added to nodeos_short_fork_take_over_lr_test. Example fail: …
=> improve reliability of two forking unit tests

CMakeLists.txt, CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in, README.md, libraries/chain/include/eosio/chain/types.hpp, plugins/chain_plugin/trx_retry_db.cpp
This PR also ticks up the git commit for the fc submodule.
Some additional test changes may be needed.
=> Update memory_size() calculation for tracked_transaction

plugins/chain_interface/include/eosio/chain/plugin_interface.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp
Original APIs hardcoded false, new compute_transaction hardcoded true, new send_transaction2 now honors parameter.
=> Implement return failure traces.

plugins/chain_interface/include/eosio/chain/plugin_interface.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp
Reverts eosnetworkfoundation/mandel#142
Our existing python tests assume exceptions on failures. This needs to be coupled with an update to your python tests to use `--use-old-send-rpc` or specify `--return-failure-trace false` or expect traces on failure and examine the trace for error.
=> Revert "Implement return failure traces."

docs/02_cleos/03_command-reference/get/transaction-status.md, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/chain_plugin/include/eosio/chain_plugin/trx_finality_status_processing.hpp, plugins/chain_plugin/test/test_trx_finality_status_processing.cpp, plugins/chain_plugin/trx_finality_status_processing.cpp, programs/cleos/httpc.hpp, programs/cleos/main.cpp, tests/chain_plugin_tests.cpp, tests/get_table_tests.cpp, tests/nodeos_run_test.py
Adding a feature that allows querying the status of a transaction on the chain.
Support for the feature added in cleos via subcommand: `get transaction-status <transaction_id>`
Feature takes a transaction_id as input and outputs chain status and, if available, transaction status in the following format:
`{
"state": "IN_BLOCK",
"block_number": 90,
"block_id": "0000005accfd59ba80a05380f60d51687406337b2aedd28b7daa33fdb8c16b5a",
"block_timestamp": "2022-04-27T16:11:26.500",
"expiration": "2022-04-27T16:11:56.000",
"head_number": 186,
"head_id": "000000bab27da51f76f483bb629b532510c22e2eb1acc632f5b37b421adecf63",
"head_timestamp": "2022-04-27T16:12:14.500",
"irreversible_number": 25,
"irreversible_id": "0000001922118216bc16bf2c60d950598d80af3beca820eab751f7beecdb29e4",
"irreversible_timestamp": …
=> Add get_transaction_status to chain_plugin

tests/CMakeLists.txt, tests/get_producers_tests.cpp
Back port test of: https://github.com/EOSIO/eos/pull/9923
The code changes of that PR are not needed, as no rocksdb backingstore in Mandel.
=> get_producers tests

tests/Cluster.py, tests/Node.py, tests/TestHelper.py, tests/block_log_util_test.py, tests/large-lib-test.py, tests/nodeos_chainbase_allocation_test.py, tests/nodeos_forked_chain_test.py, tests/nodeos_irreversible_mode_test.py, tests/nodeos_multiple_version_protocol_feature_test.py, tests/nodeos_protocol_feature_test.py, tests/nodeos_short_fork_take_over_test.py, tests/nodeos_startup_catchup.py, tests/nodeos_under_min_avail_ram.py, tests/ship_test.py
Ports EOSIO/eos#9175
> Added Node methods to analyze production delays, added reporting these at the end of tests, and changed ship_test to only identify as an error when a block is reported as received in the ship node significantly later than when it would have been produced in the producing node (it originally assumed that it was produced at the slot time, which resulted in VM hiccups delaying block production and triggering this error). Also added storing nodeId in the Node so it would not need to be passed in to so many methods.
The change for _"storing nodeId in the Node so it would not need to be passed in to so many methods"_ resolves a lot of  conflicts for future ports as it touches a lot of files.
Came over nearly verbatim except for removal of a CI change and removal of change …
=> port "Ship delay error fix" test changes

README.md, tests/release-build.sh
Refactor out the sole usage of `jq`. Python is already a requirement to run tests so lean on that instead. Removes `jq` from being a requirement.
=> refactor release-build-test to eliminate sole usage of jq

docs/01_nodeos/03_plugins/producer_plugin/index.md
Update developer documentation around subjective billing accounts that are whitelisted through having the subjective billing feature disabled on the account.  Accounts whitelisted in this manner are not subjected to the max failures limits.
=> Subjective Billing Whitelisting Dev Docs

plugins/http_plugin/http_plugin.cpp
I'd say at least once a month I see a user ensnared by the HTTP server's default maximum POST size when trying to set a "large" (512KB-1MB) contract on their account. There's even a recent open issue in b1's repo with someone who fell victim to this trap (EOSIO/eos#11085)
The reason this problem creeps up is because the WASM in the request sent to the HTTP server in keosd is encoded as a hex byte array, effectively doubling its size in the POST payload.
#153 improves the error message in this situation. But I really can't see any downside to just increasing the default limit to 2MB. This allows users to set contracts up to just under 1MB in size -- the maximum size cleos can set contract code to as-is anyways. A 2MB instead of 1MB limit would even seem unlikely to impact a nodeos RPC node …
=> increase HTTP server's default maximum POST size to 2MB

docs/02_cleos/03_command-reference/get/transaction-status.md, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, programs/cleos/main.cpp
Addresses the need to limit the exposure of the `get_transaction_status` request endpoint to those times when the _transaction-finality-status_ feature has been enabled.
Result of trying to exercise the `get_transaction_status` endpoing when chain_plugin was not configured to enable the _transaction-finality-status_.
**curl -v -d '{}' http://localhost:8788/v1/chain/get_transaction_status**
> HTTP/1.1 404 Not Found
> 
> {"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":590,"method":"handle_http_request"}]}}
Addresses the need to provide better http responses when no transaction id is provided to the `get_transaction_status` endpoint.
Previously a request without …
=> Updates to get_transaction_status handling.

libraries/chain/include/eosio/chain/protocol_feature_manager.hpp, libraries/chain/include/eosio/chain/types.hpp
`std::iterator<>` was depreciated in C++17. gcc 12 (well, actually libstdc++ 12) is getting chatty about this. Remove usage of it.
=> remove std::iterator<> usage

libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/intrinsic_mapping.hpp, libraries/chain/wasm_eosio_injection.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp
In EOSIO 2.0, two sets of WASM injection configurations were used:
* for wabt: softfloat, call depth, and checktime
* for EOS VM OC: softfloat
With the removal of wabt call depth and checktime injections are no longer required. Remove them.
=> remove unused checktime & call depth wasm injection

plugins/chain_api_plugin/chain_api_plugin.cpp
- Address issue: https://github.com/eosnetworkfoundation/mandel/issues/175
- Simplify error message returned for invalid transaction ids.
=> Simplify error message from get_transaction_status

docs/02_cleos/03_command-reference/get/transaction-status.md, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/chain_plugin/include/eosio/chain_plugin/trx_finality_status_processing.hpp, plugins/chain_plugin/test/test_trx_finality_status_processing.cpp, plugins/chain_plugin/trx_finality_status_processing.cpp
- Address issue: https://github.com/eosnetworkfoundation/mandel/issues/176
- Alleviate confusion around `last_` actually  typically meaning current when referring to blocks.  Clear up by going with a more clear definition of `earliest_`.
Transaction status result should now look like the following:
```
{
"state": "UNKNOWN",
"head_number": 11807884,
"head_id": "00b42c8c15d2a75cf8410153b637855e4842dbc18c852446b1dbf783452a41f8",
"head_timestamp": "2022-05-02T18:06:21.000",
"irreversible_number": 11807553,
"irreversible_id": "00b42b41281540815209d6d04c760b4f53ef37c3137c8dd8550f124557912ea4",
"irreversible_timestamp": "2022-05-02T18:03:29.500",
"earliest_tracked_block_id": "00b411ce8263d756c087f9b1b5636d0f05169de3764d7d52e0cd902f3bd284ec",
"earliest_tracked_block_number": 11801038
}
```
=> Rename last_tracked_* to earliest_tracked_*

plugins/net_plugin/net_plugin.cpp, tests/Node.py
This is a port of a fix from the EOS PR 11022: https://github.com/EOSIO/eos/pull/11022
Fixes:
1. nodeos_voting_lr_test. It was broken after bugfix in `Node.waitForIrreversibleBlock` where it was waiting for head instead of lib. After fix this increased execution time and lead to timeout fails.
2. nodeos_forked_chain_lr_test. It had flakiness due to race condition in head catchup and switching forks that lead to `go_away_message` being sent with status `benign_other` due to unknown block requested. Fix adding retry after closing connection.
=> fixing flakiness in voting and forked chain tests

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/chain_plugin/chain_plugin.cpp
This ports over EOSIO/eos#8848
> The implementation of the following options were changed to more closely reflect their descriptions.
> - `force-all-checks`
>          do not skip any validation checks while replaying blocks (useful for replaying blocks from untrusted source)
> - `disable-replay-opts`
>          disable optimizations that specifically target replay
>
> Previously `disable-replay-opts` was tied to skipping transaction validation checks during replay. However, the existing option `force-all-checks` is a better indication of this functionality. Now `disable-replay-opts` only disables **optimizations** during replay; specifically the creation of database undo sessions. Now `force-all-checks` enforces the additional transaction validation checks that can be skipped when blocks …
=> fixup behavior of force-all-checks & disable-replay-opts to match likely expectation

libraries/chain/transaction_context.cpp
Ports over EOSIO/eos#8250, just a simple comment spelling/grammar fix
=> Spelling correction in transaction_context::init()

libraries/chain/include/eosio/chain/database_utils.hpp
This ports over EOSIO/eos#9761
> There are a number of uses of reinterpret_cast in database_utils.hpp. They violate the strict aliasing rule.
The fix is using memcpy to assign values between non-compatible types.
=> Fix strict aliasing violations in database_utils.hpp

plugins/producer_plugin/include/eosio/producer_plugin/subjective_billing.hpp, plugins/producer_plugin/producer_plugin.cpp, unittests/api_tests.cpp
- Transactions were limited to (2 * previous_run_time) when already speculatively executed on a node. Do not impose this restriction when subjective billing is disable or disable for an account.
- Resolves #195
=> Do not limit transaction deadline if subjective billing disabled for account

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/history_api_plugin/history_api_plugin.cpp, plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp, plugins/net_api_plugin/net_api_plugin.cpp, plugins/producer_api_plugin/producer_api_plugin.cpp, plugins/test_control_api_plugin/test_control_api_plugin.cpp, plugins/wallet_api_plugin/wallet_api_plugin.cpp, tests/CMakeLists.txt, tests/Node.py, tests/plugin_http_api_test.py, unittests/CMakeLists.txt, unittests/plugin_tests.cpp
Apply parameters check for every http calls.
* If empty body is not allowed, then report `"A Request body is required"` with error code `400`.
* Require JSON body to contain data for JSON object, `{}` will report: `"A Request body is required"` with error code `400`.
* If unable to parse JSON object for http param report: `"Unable to parse valid input from POST body"` with error code `400`. 
- Resolves #198 
- Resolves #199 
- Backports https://github.com/EOSIO/eos/pull/9033 & https://github.com/EOSIO/eos/pull/9209 & https://github.com/EOSIO/eos/pull/9317
=> Add message body check (400) for http calls

plugins/chain_plugin/chain_plugin.cpp, tests/nodeos_retry_transaction_test.py
Update to not retry if there was a valid reason the transaction failed.
Add test case.  This test case will use a funds transfer that would cause an overdraw to verify it fails due to the overdraw except instead of due to expiration in the retry.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/215
=> Fix transaction retry issue

tests/trx_finality_status_forked_test.py, tests/trx_finality_status_test.py
All of our integration tests pass a large `http-max-response-time-ms` so that loading contracts does not time out on slow test machines. Added this to the two new transaction finality integration tests.
Resolves #229
=> Increase http-max-response-time-ms for tests

libraries/chain/abi_serializer.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp, plugins/txn_test_gen_plugin/txn_test_gen_plugin.cpp, programs/nodeos/logging.json
Backport transaction logging fix (and fix one additional location) to properly handle that failure traces are being returned.
Backports: https://github.com/EOSIO/eos/pull/10867
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/222
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/225
=> Transaction logging fix

plugins/wallet_plugin/wallet_plugin.cpp, programs/keosd/main.cpp
Resolves https://github.com/eosnetworkfoundation/mandel/issues/212
Preemptively create the wallet directory before set_dir is called (which erroneously attempts to lock the file wallet.lock in a non-existent directory). This change eliminates the problem of requiring that the user must explicitly create the directory before using keosd.
https://github.com/EOSIO/eos/pull/8490
=> Backported code to preemptively create wallet dir

libraries/chain/controller.cpp
Properly handle exception for db being too small for snapshot.  Original eosio PR: https://github.com/EOSIO/eos/pull/10936
Resolves https://github.com/eosnetworkfoundation/mandel/issues/232
=> cleaned up handling of failed startup from snapshot

plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
The test was dereferencing an empty `std::optional`. Fixed the code to verify that the optional has no value.
=> Fix test_trx_finality_status_processing test

tests/release-build.sh
Remove a bash4ism from this test and just use Python to convert the boolean to a known-case string. Fixes the test on macos which ships with an ancient bash
=> remove bash4 lowercase operation and just use python for release-build test

plugins/net_plugin/net_plugin.cpp, plugins/test_control_plugin/test_control_plugin.cpp
Backport: https://github.com/EOSIO/eos/pull/11016 
[heifner](https://github.com/heifner) merged 4 commits into develop-boxed from bugfixes-from-dev-to-dev-box on Jan 7
Backport: [#10593](https://github.com/EOSIO/eos/pull/10593)
back port of:
[#10590](https://github.com/EOSIO/eos/pull/10590)
[#10584](https://github.com/EOSIO/eos/pull/10584) <-- Overcome by events.
[#10580](https://github.com/EOSIO/eos/pull/10580)
Fixes are:
net_plugin bugfix for some race conditions when nodes stop syncing
test_control_plugin fix for condition when producer produces less than 12 blocks in round (due to performance issues).
test framework fixes: increased transaction expiration in Node.transferFunds and blocks range in Node.getBlockNumByTransId
Integration tests where those bugs were found: …
=> Backport some misc bugfixes from EOSIO/develop-boxed

plugins/http_plugin/http_plugin.cpp
Public API nodes with default info level logging for http_plugin have huge logs filled with:
`Dec 12 00:00:13 node1 nodeos[29695]: error 2020-12-12T00:00:13.966 nodeos    http_plugin.cpp:964           handle_exception     ] FC Exception encountered while processing chain.push_transaction
Dec 12 00:00:14 node1 nodeos[29695]: error 2020-12-12T00:00:14.061 nodeos    http_plugin.cpp:964           handle_exception     ] FC Exception encountered while processing chain.push_transaction`
Reduce this noise. Full details should be enabled via `debug` logging for private API nodes. There is no error in the system if a `push_transaction` generates an exception. That is normal operating conditions.
Backport: https://github.com/EOSIO/eos/pull/9820
Resolves: …
=> Backport: Reduce logging for failed http plugin calls

libraries/state_history/include/eosio/state_history/log.hpp
Backport https://github.com/EOSIO/eos/pull/9931
There are two printf to change in Mandel.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/245
=> trace history log messages should print nicely in syslog

plugins/db_size_api_plugin/db_size_api_plugin.cpp, tests/plugin_http_api_test.py
Backport https://github.com/EOSIO/eos/pull/9212
> Apply 400 check on db_size api "get",
> 
> If empty body or empty content body is passed in, the RPC returns with correct info, otherwise return 400.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/239
=> Apply 400 check to db_size

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Default to returning WASM as returning WAST has been deprecated.
As there is no more support for get_code to return WAST the default to return WASM should be true.
Backport https://github.com/EOSIO/eos/pull/9706
Resolves https://github.com/eosnetworkfoundation/mandel/issues/243
=> Default to returning WASM as returning WAST has been deprecated.

plugins/trace_api_plugin/CMakeLists.txt, plugins/trace_api_plugin/configuration_utils.cpp, plugins/trace_api_plugin/include/eosio/trace_api/configuration_utils.hpp
[fix duplicate symbol error in trace_api::configuration_utils - 2.1 by spoonincode · Pull Request #10672 · EOSIO/eos](https://github.com/EOSIO/eos/pull/10672) 
[spoonincode](https://github.com/spoonincode) merged 1 commit into release/2.1.x from trace_api_cfgutils_21x on Aug 30, 2021
Backport https://github.com/EOSIO/eos/pull/10672
Backport of fix in [#10670](https://github.com/EOSIO/eos/pull/10670) that was needed to compile with gcc11
Resolves https://github.com/eosnetworkfoundation/mandel/issues/235
=> Fix duplicate symbol error in trace_api::configuration_utils

plugins/chain_api_plugin/chain.swagger.yaml, plugins/chain_plugin/chain_plugin.cpp, tests/plugin_http_api_test.py
Backports: https://github.com/EOSIO/eos/pull/11014
[heifner](https://github.com/heifner) merged 2 commits into develop-boxed from fix-chain-api-get-activated-protocol-features-dev-box on Jan 5
Made the following modifications related to the get_activated_protocol_features API call:
Corrected documentation that indicated a wrong format of the POST json payload needed for this call.
When the search_by_block num was used, the range of values to act was always empty due to a bug on the lower_bound_value used for both upper_bound and lower_bound.
Added some extra checks on the integration test plugin_http_api_test to take into account the data returned by the api call.
Backports: [chain api plugin / get_activated_protocol_features modifications #9873](https://github.com/EOSIO/eos/pull/9873) …
=> Backport: chain api plugin / get_activated_protocol_features modifications

libraries/chain/include/eosio/chain/wast_to_wasm.hpp, libraries/chain/wast_to_wasm.cpp, programs/cleos/main.cpp, unittests/wasm_tests.cpp
Backport https://github.com/EOSIO/eos/pull/10819
Update cleos to not perform wasm to wast conversion.
Users can use standard WebAssembly tooling to convert from wasm to wast if needed.
Removal announcement: https://github.com/EOSIO/eos/issues/7597
Resolves https://github.com/eosnetworkfoundation/mandel/issues/274
=> cleos remove wasm to wast conversion

tests/block_log_util_test.py, tests/compute_transaction_test.py, tests/distributed-transactions-remote-test.py, tests/distributed-transactions-test.py, tests/http_plugin_test.py, tests/launcher_test.py, tests/nodeos_forked_chain_test.py, tests/nodeos_producer_watermark_test.py, tests/nodeos_run_remote_test.py, tests/nodeos_run_test.py, tests/nodeos_short_fork_take_over_test.py, tests/nodeos_startup_catchup.py, tests/nodeos_under_min_avail_ram.py, tests/nodeos_voting_test.py, tests/p2p_high_latency_test.py, tests/p2p_network_test.py, tests/prod_preactivation_test.py, tests/restart-scenarios-test.py, tests/subjective_billing_test.py, tests/terminate-scenarios-test.py, tests/trx_finality_status_forked_test.py, tests/trx_finality_status_test.py, tests/validate-dirty-db.py
Working through python tests to update them to properly report failure exit code on failure including when an exception is thrown.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/282
=> Fix all python tests to correctly report failure exit code on failure including any exception thrown.

tests/CMakeLists.txt, tests/nodeos_contrl_c_test.py
Add an integration of nodeos for crash when the nodes are killed.
Backports https://github.com/EOSIO/eos/pull/9494
Description:
Added a new integration test for nodeos. This test sets up one producing nodes and one "bridge" node using test_control_api_plugin. We send transactions to the bridge node. After the accounts are initialized and allocated with symbols, we kill the producing node. Then we flood hundreds transactions to the bridge node. At the end, we ill the bridge. It tests that no crashes happen when the nodes are killed.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/242
=> Add integration test for nodeos shutdown

plugins/producer_plugin/producer_plugin.cpp
Before the 3-strike rule (3 failed trx per block and then no more allowed per account) was only applied during processing of the unapplied transaction queue in `start_block`.  Now it is applied during "regular" block processing as well. This prevents users from flooding a BP with trxs, during their block production window, that fail and limit the amount of transactions that can be placed in a block.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/296
=> Apply 3-strike rule for complete block production - 2.0

programs/nodeos/logging.json
Resolves #91.
From eosnetworkfoundation/mandel-fc#24:
The GELF appender now supports arbitrary fields and accompanying values in the logging.json configuration file, with some restrictions.  Per the GELF specification, user-defined field names must begin with an underscore and contain only letters, numbers, underscores, dashes, and dots.  The regular expression against which field names are checked is: `^_[\w\.\-]*$`.  Beyond the format check, there is also a list of reserved field names which are reserved by the specification or used by nodeos.  The list of reserved field names is:
- _id
- _timestamp_ns
- _log_id
- _line
- _file
- _method_name
- _thread_name
- _task_name
There is no enforced limit on the length of the field name nor the accompanying value.  However, by default, Graylog …
=> Update to most recent version of the fc library.

libraries/chain/controller.cpp, plugins/producer_plugin/producer_plugin.cpp
This is a backport of logging and shutting down on fork_db exception 
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/289
=> Backported exit on fork_db corrupted

programs/cleos/main.cpp, tests/cli_test.py
Makes cleos unpack a packed txn before signing.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/291
Original PR: https://github.com/EOSIO/eos/pull/10203
=> Backport of unpacking packed transaction in cleos

tests/trx_finality_status_test.py
The integration test `trx_finality_status_test` will sometimes fail if the timing of the submitted transaction falls too close to the beginning of a producer's series.  The extra time required to achieve finality in the test network could exceed the expiration time for the successful transaction status cache being used in the test.  Increase the test expiration to compensate.
=> Bump up successful trx cache expiration to 60s in integration test.

plugins/producer_plugin/producer_plugin.cpp
Before the 3-strike rule (which is configurable now) (3 failed trx per block and then no more allowed per account) was only applied during processing of the unapplied transaction queue in start_block. Now it is applied during "regular" block processing as well. This prevents users from flooding a BP with trxs, during their block production window, that fail and limit the amount of transactions that can be placed in a block.
Resolves #296
=> Apply 3-strike rule for complete block production

tests/plugin_http_api_test.py
Add verification of feature digests to the integration test for get_activated_protocol_features
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/290
=> Add hash verification to get_activated_protocol_features test

libraries/chain/include/eosio/chain/name.hpp, plugins/resource_monitor_plugin/test/test_add_file_system.cpp, plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp, plugins/trace_api_plugin/store_provider.cpp, plugins/trace_api_plugin/test/test_compressed_file.cpp, unittests/producer_schedule_tests.cpp
Resolves a few warnings. Absolutely not exhaustive effort by any stretch, just trying to stave off the fire hose a little so I can see the trees in the forest.
The chainbase fix needs eosnetworkfoundation/mandel-chainbase#4 and its by far the biggest improvement to warnings (along with #322). The others in here are just low effort obvious `int` to `size_t` changes on for() loops, except for one that was `uint` to `int` when checking against the return of `snprintf()`. 
Also picked up eosnetworkfoundation/mandel-chainbase#3 since #277 continues to be wedged.
=> resolve a few warnings including a chainbase one that generated lots of spam

CMakeLists.txt, package.cmake, plugins/CMakeLists.txt
Adds support for building .deb and .rpm packages (and binary tarballs). This is very basic support but I have validated that packages build and install cleanly.
I've never been able to figure out how to to get `GNUInstallDirs` and `cpack` to fully cooperate with each other (a bit of a conflict due to absolute vs relative paths in `install()` commands). So when building a package you probably want to `-DCMAKE_INSTALL_PREFIX=/usr` as I believe it's generally a faux pas to have a package place files in `/usr/local`.
~Also, I have only enabled tarballs by default since if I enable `TGZ;DEB;RPM` as the default users may get confused when they can't build an .rpm on Ubuntu (it does work if you have the tools installed, it just may be a little weirdly unexpected). Maybe the default should be …
=> add cpack support to easily build .deb & .rpm packages

plugins/chain_plugin/chain_plugin.cpp
old cruft -- this option's utility was removed when chainbase was upgraded to use hugepage automatically.
=> remove old unused database-hugepage-path config option

plugins/trace_api_plugin/include/eosio/trace_api/chain_extraction.hpp, plugins/trace_api_plugin/include/eosio/trace_api/trace.hpp
Unlike `eosio/eos 2.2`, correctly handle backward compatibility with `eosio/eos 2.1`.
Resolves #337
=> trace_api_plugin eosio/eos 2.1 compatibility

plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, programs/cleos/main.cpp
Changed the parameter to the compute_transaction endpoint to be a struct in order to make it more extensible in the future.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/335
=> Modified parameter to compute_transaction

tests/launcher_test.py, tests/nodeos_run_remote_test.py, tests/nodeos_run_test.py, tests/trace_plugin_test.py
Tests are run with the working directory set to the build directory (`CMAKE_BUILD_DIR`). These four tests were erroneously looking for eosio.token.abi in, effectively, `CMAKE_BUILD_DIR/../unittests/contracts/eosio.token/eosio.token.abi`. That is only valid when the build directory is a subdirectory of the source directory; not the case for my environment, for example.
Fix these tests to look in `CMAKE_BUILD_DIR/unittests/contracts/eosio.token/eosio.token.abi` instead.
=> fix path for eosio.token.abi in tests

package.cmake
Packages are currently being named "mandel"; these won't upgrade old pre-ENF "eosio" packages, so mark them as a conflict to prevent installation.
=> mark the deb & rpm packages as conflicting with 'eosio' package

tests/chain_plugin_tests.cpp
chain_plugin_tests.cpp is missing this, which causes the test tree to get a little messed up.
Before:
```
chain_plugin_tests*
get_block_with_invalid_abi*
get_account*
get_producers_tests*
get_producers*
get_producers_from_table*
get_table_tests*
get_scope_test*
get_table_test*
get_table_by_seckey_test*
get_table_next_key_test*
wallet_tests*
wallet_test*
wallet_manager_test*
wallet_manager_create_test*
```
After
```
chain_plugin_tests*
get_block_with_invalid_abi*
get_account*
get_producers_tests*
get_producers*
get_producers_from_table*
get_table_tests*
get_scope_test*
get_table_test*
get_table_by_seckey_test*
get_table_next_key_test*
wallet_tests*
wallet_test*
wallet_manager_test*
wallet_manager_create_test*
```
=> add missing BOOST_AUTO_TEST_SUITE_END() to chain_plugin_tests.cpp

package.cmake
Before this change, package filenames would look like `mandel-3.1.0.deb`, for example. Add the architecture and (when building on Ubuntu or EL) the platform version to the filename.
Now packages will be named something like `mandel-3.1.0-ubuntu20.04-x86_64.deb` and `mandel-3.1.0-el7-x86_64.rpm`
=> add platform, platform version, and architecture to package file name

libraries/chain/webassembly/crypto.cpp, libraries/chain/webassembly/privileged.cpp
change `fc::public_key::which()` & `fc::signature::which()` to return a `size_t` which is what the underlying storage (`std::variant`) is going to return anyways. No reason to convert to `int` on return. Silences some warnings.
Back out some preexisting casts to `unsigned` that were likely squelching warnings in the past that are no longer needed.
Needs eosnetworkfoundation/mandel-fc#33 and apparently eosnetworkfoundation/mandel-fc#32 & eosnetworkfoundation/mandel-fc#30 are coming along for the ride.
=> change which() for public_key & signature to return size_t silencing some warnings

plugins/state_history_plugin/state_history_plugin.cpp
As such, this error is now being suppressed. It will still be logged, but not as an error. This "End of file" came through when a connection (socket) was being closed.
=> Suppress "End of file" error reporting in SHiP

README.md
I'm 100% certain more deps are listed here than strictly required. But the ccache one worries me a little since libff does pick it up and the force usage of it automatically. Would like to remove it from this list users are likely to copy/paste
=> remove ccache from deps listed in README

libraries/testing/include/eosio/testing/tester.hpp, unittests/main.cpp
> Allow Boost.Test to report the last checkpoint location when an exception is thrown.
backports https://github.com/EOSIO/eos/pull/8677
Resolves https://github.com/eosnetworkfoundation/mandel/issues/380
=> Boost.Test to report the last checkpoint location

tests/Node.py
Backports: https://github.com/EOSIO/eos/pull/10103
From https://github.com/EOSIO/eos/pull/10103:
Consider the following scenario:
The overall plan is to activate a total of 17 protocol features.
The first 5 protocol features are activated and added to some block (let's say block 18).
While still on block 18, the remaining 12 protocol features transactions are executed (and they will be added to block 19, and the features will be active on block 20), and the check for waitForHeadToAdvance also gets executed while we are still on this block 18.
When the chain advances to block 19, the waitForHeadToAdvance method returns, but only 5 protocol features are really activated, leading to a state on the chain where we return from this method, but the protocol features are in realityy still not …
=> plugin_http_api_test - fix timing issue

plugins/net_plugin/net_plugin.cpp
* Delay `net_plugin` connecting to its peers until after all plugins have started. This allows replay to finish first before attempting to connect.
* Close connection on sync timeout, with immediate re-connect, since something is likely wrong with the connection.
Resolves #369
=> net_plugin delay connecting to peers

plugins/net_plugin/net_plugin.cpp, tests/Node.py
* Delay `net_plugin` connecting to its peers until after all plugins have started. This allows replay to finish first before attempting to connect.
* Close connection on sync timeout, with immediate re-connect, since something is likely wrong with the connection.
Merges #381 to main.
=> net_plugin delay connecting to peers [main]

package.cmake
turns out a cmake `file(READ` is a fatal error when the file doesn't exist.
=> before reading /etc/os-release make sure it exists - 3.1

package.cmake
Merge in of 3.1's #417
turns out a cmake `file(READ` is a fatal error when the file doesn't exist.
=> before reading /etc/os-release make sure it exists - main

programs/cleos/main.cpp
Example error now:
```
./cleos -u http://127.0.0.1:8882 get info
Failed http request to nodeos at http://127.0.0.1:8882; is nodeos running?
Error: connect: Connection refused
```
Resolves #428
=> Remove confusing error message - 3.1

programs/cleos/main.cpp
Example error now:
```
./cleos -u http://127.0.0.1:8882 get info
Failed http request to nodeos at http://127.0.0.1:8882; is nodeos running?
Error: connect: Connection refused
```
Merges #480 into main.
=> Remove confusing error message - main

libraries/chain/platform_timer_asio_fallback.cpp
Backport https://github.com/EOSIO/eos/pull/9331. GH issue https://github.com/eosnetworkfoundation/mandel/issues/460.
In the original code, `get_future` and `set_value` run on different threads and can cause a race condition when modifying/accessing the promise object at the same time. Change to call `get_future` at the beginning.
=> Get future before use to avoid race on set_value get_future

scripts/pinned_build.sh
https://github.com/eosnetworkfoundation/mandel/issues/363 reports `pinned_build.sh` always prints "Currently only supporting Ubuntu based builds. Proceed at your own risk.", even on Ubuntu platform.
https://github.com/eosnetworkfoundation/mandel/issues/364 reports the build directory is made relative to the dependency directory; it should have been relative to the directory where the script starts.
This PR fixes those two issues.
Tested in two different directories:
```
scripts/pinned_build.sh ~/dep build 16
./pinned_build.sh ~/dep build 16
```
=> Print out warning only if the platorm is not Ubuntu and make build directory relative to where the build starts - 3.1

plugins/state_history_plugin/state_history_plugin.cpp, tests/CMakeLists.txt, tests/ship_streamer.cpp, tests/ship_streamer_test.py, tests/ship_test.py
`head` not updated until after `accepted_block` signal is emitted. This prevents controller `fetch_block_by_number` from returning the current block signaled. Work around this issue by using the signaled block_state and `get_block_id_for_num` method.
Added new SHiP streamer client that will stream blocks from SHiP. It doesn't support ABI currently, so blocks, traces, and deltas are all in hex. Added new python integration test that uses the SHiP streamer to verify blocks are returned from SHiP.
Example output from ship_streamer:
```
./tests/ship_streamer --start-block-num 253185406 --end-block-num 253185407 --fetch-block --fetch-traces
[
{ "get_blocks_result_v0":
{
"head": {
"block_num": 253185721,
"block_id": "0F174EB908AAB71C735163B7AE4419A6B63F56654A71FBD864F2E55D72086AC7"
}, …
```
=> Fix issue with current block not sent to SHiP clients - 3.1

plugins/state_history_plugin/state_history_plugin.cpp, scripts/pinned_build.sh, tests/CMakeLists.txt, tests/ship_streamer.cpp, tests/ship_streamer_test.py, tests/ship_test.py
`head` not updated until after `accepted_block` signal is emitted. This prevents controller `fetch_block_by_number` from returning the current block signaled. Work around this issue by using the signaled block_state and `get_block_id_for_num` method.
Added new SHiP streamer client that will stream blocks from SHiP. It doesn't support ABI currently, so blocks, traces, and deltas are all in hex. Added new python integration test that uses the SHiP streamer to verify blocks are returned from SHiP.
Example output from ship_streamer:
```
./tests/ship_streamer --start-block-num 253185406 --end-block-num 253185407 --fetch-block --fetch-traces
[
{ "get_blocks_result_v0":
{
"head": {
"block_num": 253185721,
"block_id": "0F174EB908AAB71C735163B7AE4419A6B63F56654A71FBD864F2E55D72086AC7"
}, …
```
=> Fix issue with current block not sent to SHiP clients - main

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/test/test_account_query_db.cpp, plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
`/v1/chain/get_accounts_by_authorizers` was designed to support multi-threaded calls. However, it was not hooked up to the http thread handling code, but instead was hooked up to the normal app thread handling.
Fixed `http_plugin.hpp add_async_api` to actually call `add_async_handler`.
Added a multi-threaded test to verify `get_accounts_by_authorizers` works from different thread.
Moved `/v1/chain/get_transaction_status` from `add_async_api` to `add_api` since it does not support multi-threaded reads.
Resolves #204
=> Make /v1/chain/get_accounts_by_authorizers multi-threaded

plugins/http_plugin/http_plugin.cpp
> The query object has been deprecated since boost 1.66.  Incidentally
> resolves #5422 when using TCP on a system with only loopback configured.
>   The preferred boost API no longer defaults to the `address_configured`
> flag.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/396
=> Eliminate use of boost deprecated query object.

programs/cleos/main.cpp
> Replace get_abi with get_raw_abi to fetch abi file, then convert the raw abi to abi before sending back to the requestor.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/397
=> Using get raw abi in cleos

programs/cleos/main.cpp
> Replace hard coding "eosio" to name(config::system_account_name).to_string()
Resolves https://github.com/eosnetworkfoundation/mandel/issues/390
=> Replace hard coding system_account_name 

CMakeLists.txt, tests/CMakeLists.txt
asio depends on boost system and prior to boost 1.69 boost system is an actual library that needs to be linked with. Since we do claim support for boost 1.67+, this is clearly a defect, and this is the only problem using boost 1.67 (on Debian 10), let's fix it.
=> fix linking of c++ SHIP tests on boost versions prior to 1.69 - 3.1

programs/cleos/main.cpp
https://github.com/EOSIO/eos/pull/9068
This sub-command takes a signed transaction, validates the signatures on it, and outputs a JSON array of the recovered public keys.
`cleos validate signatures <json_file_of_transaction>`
Example:
```
./cleos create account -j -d --json-file t eosio kevinh EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
{
"expiration": "2022-06-23T00:50:08",
"ref_block_num": 4714,
"ref_block_prefix": 3530990,
"max_net_usage_words": 0,
"max_cpu_usage_ms": 0,
"delay_sec": 0,
"context_free_actions": [],
"actions": [{
"account": "eosio",
"name": "newaccount",
"authorization": [{
"actor": "eosio",
"permission": "active"
}
],
"data": "0000000000ea305500000000b4e9b68201000000010002c0ded2bc1f1305fb0faac5e6c03ee3a19242 …
```
=> Backport of the cleos validate signatures

libraries/chain/include/eosio/chain/resource_limits.hpp, libraries/chain/resource_limits.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, programs/cleos/main.cpp, unittests/resource_limits_test.cpp
Updated `/v1/chain/get_account`. See https://github.com/eosnetworkfoundation/mandel/issues/398 for complete details.
> For issue https://github.com/EOSIO/eos/issues/8708,
> Added last_updated_time_stamp and current_used (according to the head block timestamp) to get_account results.
> 
> The current_used is shown on the same line following used ( in parenthesis).
> The last_updated_time_stamp will only be printed in the json result.
> 
> Note:
> 
> The old cleos (w/o this fix) prints the same info on screen with no matter of new or old version of nodeos , but json format has those two fields from new nodeos.
> The new cleos (with this fix) displays (out-of-date) for current_used with the old version of nodeos.
> When an account has unlimited cpu/net usage, (unlimited) is displayed for …
=> Add additional CPU/NET usage data to get_account results

CMakeLists.txt, tests/CMakeLists.txt
main merge of #505
asio depends on boost system and prior to boost 1.69 boost system is an actual library that needs to be linked with. Since we do claim support for boost 1.67+, this is clearly a defect, it's a small fix, and this is the only problem using boost 1.67 (on Debian 10), let's fix it.
=> fix linking of c++ SHIP tests on boost versions prior to 1.69 - main

libraries/chain/include/eosio/chain/transaction.hpp
https://github.com/EOSIO/eos/pull/9147
Good fix of comments.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/402
=> Backport: two comment fixes to transaction.hpp

CMakeLists.txt, CMakeModules/EosioTesterBuild.cmake.in, README.md
Fix issues seen with libff when trying to use mandel with mandel.cdt.
Update CMakeLists.txt to create a parallel mandel-config.cmake for use until mandel goes through renaming.
Update path to libff in fc libraries when using build from src.
Add install directions for current mandel use with mandel.cdt (or others).
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/426
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/420
Supersedes: https://github.com/eosnetworkfoundation/mandel/pull/421
Relates to mandel.cdt issue/PR:
https://github.com/eosnetworkfoundation/mandel.cdt/issues/25
https://github.com/eosnetworkfoundation/mandel.cdt/pull/26
=> fix libff in 3.1 tester cmakes

scripts/install_deps.sh, scripts/pinned_build.sh
Resolves #356 but also other issues I've encountered when using the script on all Ubuntu versions: python needs to be installed, and on Ubuntu 18 it's an old cmake so can't use `-S` argument on cmake
=> misc pinned build script fixes - 3.1

programs/cleos/httpc.cpp
Backport https://github.com/EOSIO/eos/pull/9349
Resolve https://github.com/eosnetworkfoundation/mandel/issues/430
From the original PR:
- Upgrades cleos http 1.0 to 1.1: in more advanced cloud stacks cleos is being rejected by gateways or proxies with HTTP status 426:
The HTTP 426 Upgrade Required client error response code indicates that the server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol. The server sends an Upgrade header with this response to indicate the required protocol(s).
- Removes unnecessary json parsing if it's an error code
- Straight dump responses for --print-response if unable to convert to variant
=> [3.2] cleos Http 1.1 support and improves response handling

programs/cleos/httpc.cpp
Backport https://github.com/EOSIO/eos/pull/10070
Resolve https://github.com/eosnetworkfoundation/mandel/issues/413
Make `cleos` print out non-JSON formatted HTTP responses (errors).
=> [3.2] CLEOS -- prints out non-JSON formatted HTTP responses

unittests/snapshot_tests.cpp
Backport https://github.com/EOSIO/eos/pull/9975
Resolve https://github.com/eosnetworkfoundation/mandel/issues/438
Added a second account and action to exhaustive_snapshot test to exercise more execution paths.
=> [3.2] Add a second account and action to test_exhaustive_snapshot

libraries/chain/include/eosio/chain/abi_serializer.hpp, programs/eosio-launcher/main.cpp
Merge issue of https://github.com/eosnetworkfoundation/mandel/pull/190 missed trimming the "hex_data" attribute in logged transaction trace data.
Added `transaction_trace_success` and `transaction_trace_failure` trace loggers to `eosio-launcher` to provide additional logging during tests.
Example:
`debug 2022-06-25T18:48:07.183 nodeos    producer_plugin.cpp:642       operator()           ] [TRX_TRACE] Speculative execution is ACCEPTING tx: {"id":"17ad680cbb16e142f0fc4e0b50a0a5be59362098056c969bb5a7ee00e9beee1c","block_num":18,"block_time":"2022-06-25T18:48:07.500","producer_block_id":null,"receipt":{"status":"executed","cpu_usage_us":2721,"net_usage_words":878},"elapsed":5525,"net_usage":7024,"scheduled":false,"action_traces":[{"action_ordinal":1,"creator_action_ordinal":0,"closest_unnotif …
=> [3.1] Fix log trimming of hex_data JSON output.

libraries/chain/include/eosio/chain/abi_serializer.hpp, programs/eosio-launcher/main.cpp
Merge issue of https://github.com/eosnetworkfoundation/mandel/pull/190 missed trimming the "hex_data" attribute in logged transaction trace data.
Added `transaction_trace_success` and `transaction_trace_failure` trace loggers to `eosio-launcher` to provide additional logging during tests.
Example:
`debug 2022-06-25T18:48:07.183 nodeos    producer_plugin.cpp:642       operator()           ] [TRX_TRACE] Speculative execution is ACCEPTING tx: {"id":"17ad680cbb16e142f0fc4e0b50a0a5be59362098056c969bb5a7ee00e9beee1c","block_num":18,"block_time":"2022-06-25T18:48:07.500","producer_block_id":null,"receipt":{"status":"executed","cpu_usage_us":2721,"net_usage_words":878},"elapsed":5525,"net_usage":7024,"scheduled":false,"action_traces":[{"action_ordinal":1,"creator_action_ordinal":0,"closest_unnotif …
=> [3.2] Fix log trimming of hex_data JSON output.

programs/cleos/main.cpp, tests/Node.py, tests/nodeos_run_test.py
> https://github.com/EOSIO/eos/pull/9021
> 
> Add the ability to use the authority struct when using cleos system newaccount
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/400
=> [3.2] Add authority structure to cleos system newaccount 

unittests/CMakeLists.txt
Backport https://github.com/EOSIO/eos/pull/9160. Resolve https://github.com/eosnetworkfoundation/mandel/issues/424.
https://github.com/EOSIO/eos/pull/9160 contained fixes for `EOSIO`, `appbase`, and `eosio-wasm-spec-tests`. The fix for `eosio-wasm-spec-tests` was already in `historical-v2.1.x` and `main`; no further work is required for that. This PR only pulls in changes from `EOSIO` and `appbase`.
=> [3.2] Backport: Fix build when build path has spaces for mandel and appbase

libraries/chain/apply_context.cpp, libraries/chain/transaction_context.cpp, unittests/api_tests.cpp
> Skip context_free_action execution during light validation.
> Since context free actions are designed not have any side-effects (except for possible console output) and to only influence execution via asserting, the fact that they exist in a signed block is indication that the producer executed them and they didn't assert. Therefore, they can be skipped during light validation where producers are implicitly trusted.
> Any node that wishes to include all context free action console output in action traces needs to run with --force-all-checks for replay, run with no trusted producers, and run in full validation mode. [NOTE: this is currently not completely accurate as it depends on PR Skip checks [ #8848]](https://github.com/EOSIO/eos/pull/8848)
Part of …
=> [3.2] skip context free actions during light validation

plugins/http_plugin/http_plugin.cpp
Backport https://github.com/EOSIO/eos/pull/9431, resolve #431.
Notes about backport: current http_plugin.cpp was already ahead of https://github.com/EOSIO/eos/pull/9431 and the PR had several commits going back and forth changes. Those made cherry-picking all the commits impossible. The first main commit was cherry-picked. The remaining ones were manually pulled in.
From original PR:
Added a new option for 'http-plugin': `http-max-in-flight-requests`. It restricts the maximum requests the flight can hold if `--http-max-in-flight-requests` = positive number. If the limit exceeds, it sends a 429 error to the client. if -`-http-max-in-flight-requests`= -1, there is no limit so the feature is turned off. It protects non-producing `nodeos` against the flood of requests when it cannot get new …
=> [3.2] Add --http-max-in-flight-requests to http_plugin option

programs/cleos/main.cpp, tests/Node.py, tests/nodeos_run_test.py
unpack data when forming transaction, useful for example when signing the transaction with trezor wallets
Change Description
In cleos unpack data when forming transaction, useful for example when signing the transaction with trezor wallets
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/579
Related to: https://github.com/eosnetworkfoundation/mandel/issues/427
=> [3.2] Backport unpack transaction data

programs/cleos/main.cpp, tests/Node.py, tests/nodeos_run_test.py, tests/testUtils.py
Use an abi_serializer to unpack transaction data for signing, also add a test case for signing transaction.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/399
Relates to: https://github.com/eosnetworkfoundation/mandel/issues/427
=> [3.2] Backport: Fix unpack data for signing transaction

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, unittests/restart_chain_tests.cpp
> Provides two new unit tests for block replay, one for regular transactions, one with context free data.
backports: https://github.com/EOSIO/eos/pull/8847
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/557
=> [3.2] Add block replay test

tests/CMakeLists.txt, tests/light_validation_sync_test.py
> backports: https://github.com/EOSIO/eos/pull/8851
> Add an integration test for messaging syncing between a production node and a light validation node.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/558
=> [3.2] Add light validation sync test

.github/workflows/jiraIssueCreator.yml
Create github workflow to create new jira issues when github issues are labeled OCI.
=> Github workflow to create new jira issues on OCI label

plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp, plugins/trace_api_plugin/store_provider.cpp
Failure https://github.com/eosnetworkfoundation/mandel/runs/7143297502?check_suite_focus=true pointed to an issue in shutdown of the `trace_api_plugin`.
`slice_directory::stop_maintenance_thread()` sets atomic bool `_maintenance_shutdown = true` and calls `notify_one()` on the `_maintenance_condition` condition variable. This is a race condition because it doesn't acquire the condition variable mutex setting up the possibility that `_maintenance_shutdown ` can be set to `true` and `notify_one` called after the while check in `slice_directory::start_maintenance_thread`  but before the `wait()` causing it to wait forever. This then blocks the `slice_directory::stop_maintenance_thread()` call of `join()` on the main thread, blocking the shutdown of all other plugins.
Changed the logic to …
=> [3.1] Fix race condition on trace_api_plugin shutdown

CONTRIBUTING.md
merge to main of #566 with some fixups for CONTRIBUTING.md
=> [3.1 -> main] fixup CONTRIBUTING.md

.github/workflows/jiraIssueCreator.yml
For now, remove github issue body as it will often break json format without some additional work.  For now just include the github issue link.
=> [3.2] Update jiraIssueCreator.yml

libraries/chain/CMakeLists.txt, libraries/testing/CMakeLists.txt
Backport https://github.com/EOSIO/eos/pull/10310. Resolve https://github.com/eosnetworkfoundation/mandel/issues/463.
Original change description:
AFAIK no one has attempted a MSVC build in years. These aren't even right anyways. Remove this old cruft.
=> [3.2] remove old outdated MSVC paths in cmake files

README.md
Various improvements and/or opinionated changes to the README.md
* Document how to do a manual build on Ubuntu 18.04 (resolves #512)
* Warn about high `-j` values (resolves #512)
* Make clear that `main` is for development not production and send users over to the releases page to get latest release & tag info; remove the release 3.0 & release 3.1 mentions as that list will just grow forever over time.
* Encourage users to grab the binaries from the release page instead of building.
* Don't use pessimistic language around distro support; be more positive and mention other distros or platforms we're treating "best-effort" even though we don't support them.
* Remove the `full-version-label-test|release-build-test|print-build-info-test` test exceptions. Day-to-day devs might not want those …
=> [3.1] various README.md improvements w.r.t. build & branches

CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in, unittests/crypto_primitives_tests.cpp
=> [3.1] Allow zero in alt_bn128; fix gmp linking in EosioTester

CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in, unittests/crypto_primitives_tests.cpp
Brings https://github.com/eosnetworkfoundation/mandel/pull/608 into `main`.
=> [3.1 -> main] Allow zero in alt_bn128; fix gmp linking in EosioTester

libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/memory.hpp, libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp
Resolve https://github.com/eosnetworkfoundation/mandel/issues/612
Fix the following warnings. Please double check if my fixes for `memory.cpp` and `executor.cpp` do not break anything. Thanks.
```
.../libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/memory.hpp:53:32: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
53 |       static_assert(-cb_offset == EOS_VM_OC_CONTROL_BLOCK_OFFSET, "EOS VM OC control block offset has slid out of place somehow");
.../libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp: In constructor ‘eosio::chain::eosvmoc::memory::memory(uint64_t)’:
.../libraries/chain/webassembly/runtimes/eos-vm-oc/memory.cpp:37:25: warning: ‘last’ may be used uninitialized in this function …
```
=> [3.2] Fix compile warnings in eos-vm-oc's memory.hpp, executor.cpp, and memory.cpp

package.cmake
When packing the experimental mandel-dev package need to more mindful when trying to discover the llvm-dev package currently in use. (we need to discover this because for some version of Ubuntu we don't know if someone used llvm-11-dev or llvm-10-dev or llvm-9-dev or ... yes all those are available in Ubuntu 20.04). If we're not mindful when doing the discovery we can accidentally stick an empty dependency in to the dependency list leading to a Bad Time.
First off, don't even perform the discovery if `LLVM_CMAKE_DIR` isn't set, which will be the case on something like aarch64 (arm8) where EOS VM OC isn't supported ergo there is no dep on llvm in the first place.
Second, ouch that `LLVM_PKG_FIND_RESULT EQUAL 0` check is no good because like a pipe on the command line it only gets you the …
=> [3.1] ensure an empty llvm-dev dep doesn't make its way to mandel-dev .deb

package.cmake
main port of #618 for ensuring dependency list in the experimental -dev package doesn't end up with an empty package when failing to discover llvm package
=> [3.1 -> main] ensure an empty llvm-dev dep doesn't make its way to mandel-dev .deb

programs/cleos/main.cpp
Resolved https://github.com/eosnetworkfoundation/mandel/issues/619
Fixed the following warnings. Now `cleos main.cpp` compiles without any warnings.
```
.../programs/cleos/main.cpp: In function ‘fc::variant push_transaction(eosio::chain::signed_transaction&, const std::vector<fc::crypto::public_key>&)’:
.../programs/cleos/main.cpp:503:112: warning: ‘static void eosio::chain::abi_serializer::to_variant(const T&, fc::variant&, Resolver, const fc::microseconds&) [with T = eosio::chain::signed_transaction; Resolver = <lambda(const eosio::chain::name&)>]’ is deprecated: use the overload with yield_function_t[=create_yield_function(max_serialization_time)] [-Wdeprecated-declarations]
503 |             abi_serializer::to_variant(trx, unpacked_data_trx, abi_serializer_resolver, …
```
=> [3.2] fixing compile warnings in cleos main.cpp

unittests/CMakeLists.txt, unittests/state_history_tests.cpp
Currently there are no SHiP unit tests.  Backport an initial tranche of unit tests.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/597
=> Backport SHiP tests 

plugins/wallet_plugin/se_wallet.cpp
On ARM macOS, every application must be signed. And Apple really means that: when you `cc hello.c -o hello` the linker adds an "ad-hoc" code signature to the output (this is not to be confused with Ad Hoc Distribution Profiles; something else entirely in the Apple code signing space).
When the Secure Enclave wallet code starts up (which is included in every macOS build), it performs a simple check to see if the executable is signed before granting access to the Secure Enclave wallet (an application needs to be signed to have proper entitlements to access the Secure Enclave). Well, this ad-hoc code signature is indeed _a_ code signature so this check passes and shows the Secure Enclave wallet in keosd even when you can't use it (because an ad-hoc signature isn't going to have the proper …
=> before enabling Secure Enclave wallet require code be signed with a certificate

plugins/net_plugin/net_plugin.cpp
Backports: https://github.com/eosnetworkfoundation/mandel/pull/495 Send handshake for heartbeat/2 if no block (first commit)
* Send handshake message if we have not seen or sent a block for heartbeat/2.
* Always send handshake message even if it has not changed since it was last sent.
Additional changes in second commit:
* Main change is to always start syncing from LIB instead of HEAD.
* See https://github.com/eosnetworkfoundation/mandel/issues/623#issuecomment-1179463090 
* Change default keepalive interval to 10s. Previous default of 32s seems rather excessive given that block time is 500ms.
* Honor keepalive interval regardless of protocol version since there is nothing that requires a particular protocol version.
=> [3.1] Fix for block producer stuck in coma state

plugins/net_plugin/net_plugin.cpp
Backports: https://github.com/eosnetworkfoundation/mandel/pull/495 Send handshake for heartbeat/2 if no block (first commit)
* Send handshake message if we have not seen or sent a block for heartbeat/2.
* Always send handshake message even if it has not changed since it was last sent.
Additional changes in second commit:
* Main change is to always start syncing from LIB instead of HEAD.
* See https://github.com/eosnetworkfoundation/mandel/issues/623#issuecomment-1179463090 
* Change default keepalive interval to 10s. Previous default of 32s seems rather excessive given that block time is 500ms.
* Honor keepalive interval regardless of protocol version since there is nothing that requires a particular protocol version.
Release 3.1.x version #627
=> [3.1 -> main] Fix for block producer stuck in coma state

plugins/producer_plugin/CMakeLists.txt, plugins/producer_plugin/include/eosio/producer_plugin/pending_snapshot.hpp, plugins/producer_plugin/pending_snapshot.cpp, plugins/producer_plugin/producer_plugin.cpp, plugins/producer_plugin/test/CMakeLists.txt, plugins/producer_plugin/test/test_snapshot_information.cpp
Resolves #434 Backport: add snapshot_information to producer_plugin test
Backports snapshot information test and refactors pending snapshot into its own header/source files.
=> [3.2] Add snapshot test and refactor pending_snapshot

plugins/http_plugin/http_plugin.cpp, plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Current http request handlers always return the json string converted from fc::variant, it is not allowed to make HTTP-RPC with empty response. (At least, it will have "null" in the case of `fc::variant()`)
I [conr2d] am writing `jsonrpc_plugin` working upon `http_plugin`, and when request is given without "id" (it's called notification), JSONRPC server must not reply to it. This patch makes it possible to create API with empty response.
Backport of https://github.com/EOSIO/eos/pull/9633
Resolves #435 
Thanks @conr2d
Co-Authored-By: [conr2d@gmail.com](mailto:conr2d@gmail.com)
=> [3.2] Allow HTTP-RPC with empty response

libraries/chain/include/eosio/chain/database_utils.hpp
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/439
Needs: https://github.com/eosnetworkfoundation/mandel-fc/pull/42
=> [3.2] Backport: move fc::blob to/from_variant out of libchain to fc

plugins/chain_plugin/test/CMakeLists.txt, plugins/chain_plugin/test/test_chain_plugin.cpp
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/441
> populates few of the fields of get_account_results struct. Add unit tests to verify the populated values.
=> [3.2] Backport: Add unit tests for new fields get account in chain_plugin

tests/plugin_http_api_test.py
This is a temporary triage for this test that can be replaced by the fixes from https://github.com/eosnetworkfoundation/mandel/issues/589
The test was failing locally because it was using the default config dir, and due my local version of that dir predating some of the features for the test, was resulting in failures. By using a custom config dir that is cleaned up, the failure case should now be avoided. 
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/553
=> [3.2] force the plugin_http_api_test to use a custom config dir

tests/Cluster.py
Fix `getClientVersion`.
`getClientVersion` now returns a version format as expected from `cleos version client`  (ex. `3.2.0-dev`)
If `fullVersion` is enabled (`fullVersion=True`), `cleos version full` will be returned which includes commit version (ex. `3.2.0-dev-f04f8baed26b2c56ae67d51f2ba6d41e494c0f47-dirty`)
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/465
=> [3.2] Backport: fix wrong cleos version returned in getClientVersion of tests/Cluster.py

libraries/chain/deep_mind.cpp, libraries/chain/include/eosio/chain/deep_mind.hpp, libraries/chain/transaction_context.cpp
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/651
Looking at the deep-mind plugin, the version that has been integrated into eosio v2.1 writes signed transactions into the dmlog on `PUSH_CREATE` deferred transactions, see [here](https://github.com/EOSIO/eos/blob/release/2.1.x/libraries/chain/transaction_context.cpp#L695).
The current mandel seems to use the packed transaction instead though, see [here](https://github.com/eosnetworkfoundation/mandel/blob/main/libraries/chain/deep_mind.cpp#L225). This should be only used for `MODIFY_CREATE` while `PUSH_CREATE` should write the signed transaction.
=> [3.1] Use signed transaction for PUSH_CREATE action deep-mind logging.

libraries/CMakeLists.txt
> Once upon a time in an eosio version long ago, the sole mechanism to populate the version displayed by, say, nodeos --version was via appbase discovering the version by git describe. At some point we changed this up a bit and the bottom line is that libraries/version is the only location that probes git for creating a string ultimately baked in to the build.
> 
> This makes the git describe in appbase a complete waste as its output is never included in to final executables. Since this git describe is run literally every time performing a make, seemed worth the trouble to disable it.
Needs https://github.com/eosnetworkfoundation/mandel-appbase/pull/9
Resolves https://github.com/eosnetworkfoundation/mandel/issues/442
=> [3.2] disable appbase's automatic version discovery via git

libraries/chain/deep_mind.cpp, libraries/chain/include/eosio/chain/deep_mind.hpp, libraries/chain/transaction_context.cpp
[3.1 -> main] https://github.com/eosnetworkfoundation/mandel/issues/651 Use signed transaction for PUSH_CREATE action deep-mind logging.
[3.1 -> main] https://github.com/eosnetworkfoundation/mandel/pull/646 make fc::read_file_contents() check for errors instead of silently returning empty string
=> [3.1 -> main] Bring GH-651 and GH-646 into main

plugins/chain_plugin/chain_plugin.cpp, plugins/producer_plugin/test/test_trx_full.cpp
Use new appbase method caller
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/447
Needs: https://github.com/eosnetworkfoundation/mandel-appbase/pull/11
=> [3.2] Backport: Use new appbase method caller

tests/CMakeLists.txt, tests/nodeos_extra_packed_data_test.py
> https://github.com/EOSIO/eos/pull/9915
> New python test to check that LIB is not stuck in case of extra data added manually to packed transaction
>We are not setup to include the nodeos_extra_packed_data_multiversion_test, but nodeos_extra_packed_data_test is doable.
I have removed the multiversion portion of the test as requested in the issue.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/436
=> [3.2] extra transaction data integration test

libraries/chain/controller.cpp
This change adds following logic:
- all exceptions  except system_error are propagated. system_error happens for example if database do not exist and needs to be created
- if chain_id cannot be retrieved empty variant returned, get replaced with find
=> [3.2] controller::extract_chain_id_from_db() does not properly handle dirty db

tests/trx_finality_status_test.py
Remove hardcoded `totalNodes`. Test was designed to have at least 2 more speculative nodes than block producers. Looks like an accidental hardcoded value as introduced into the test.
Resolves #677
=> [3.1 -> main] Fix trx_finality_status_test

libraries/chain/abi_serializer.cpp, libraries/chain/include/eosio/chain/abi_serializer.hpp
Partly support using std::array in smart contract
```
Now std::array can be used in function, in struct, and also OK to nested using.
However, std::array can't be as parameter or return of an ACTION so far.
```
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/526
Relates to: https://github.com/eosnetworkfoundation/mandel.cdt/pull/36
=> [3.2] Merge pull request #10727 from EOSIO/keke_epe948

unittests/auth_tests.cpp, unittests/misc_tests.cpp
> Demonstrate creating a public key directly from a hash with no known private key.
> public key with no known private key: EOS5JU1RRZkMdzuRFubAXFasH2WfvPdJ8fKesxfJgh1dhcmkUfuw5Y
> https://github.com/EOSIO/eos/pull/10838
Resolves https://github.com/eosnetworkfoundation/mandel/issues/452
=> [3.2] Add tests for creating public key with no private key

programs/cleos/httpc.hpp, programs/cleos/main.cpp
Backport https://github.com/EOSIO/eos/pull/10036 spiritually. Resolve https://github.com/eosnetworkfoundation/mandel/issues/462
Add `get supported_protocol_features` and `system activate` to `cleos` such that protocol features can be activated by using their names; no feature digests are needed.
The feature was totally rewritten. Hardcodied protocol feature names and digests are removed. User can use `get supported_protocol_features` to find a list of supported feature names. Command description was cleaned up and `PREACTIVATE_FEATURE` was removed as it is not possible to activate it using `activate` action from `eosio.boot` (RPC `schedule_protocol_feature_activations` must be used).
1. Find supported protocol features
```
./cleos get supported_protocol_features …
```
=> [3.2] cleos: add get supported_protocol_features and system activate subcommands

docs/00_install/01_build-from-source/00_build-unsupported-os.md, docs/00_install/01_build-from-source/index.md, docs/00_install/index.md
Added FreeBSD build instruction into docs. Its officially not supported, however it builds/runs/passes tests perfectly and instructions can be a useful for BSD users.
=> Added FreeBSD build instructions

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/net_api_plugin/net_api_plugin.cpp, programs/cleos/httpc.hpp, programs/cleos/main.cpp
> https://github.com/EOSIO/eos/pull/10898
> 
> Add chain api endpoint and cleos get command to retrieve consensus parameters.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/453
=> [3.2] Add chain api get_consensus_parameters

libraries/chain/include/eosio/chain/abi_serializer.hpp, unittests/abi_tests.cpp
Backport of action serialization to always include hex_data.
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/659
=> [3.2] Backport action serialization to always include hex_data.

libraries/chain/abi_serializer.cpp
`abi_serializer.cpp` does a
```c++
using namespace boost;
```
Apparently something internal to boost has been reorganized and when building with boost 1.80 beta it appears this `pack_unpack<float128_t>()` is getting confused with `boost::float128_t`  (gets a `template argument deduction/substitution failed` error).
Remove the broad `using namespace boost` to eliminate the conflict. This is arguably a cleaner short term spot fix than #638. If accepted I will open a ticket for a more broad fix across the code base in 3.2 (likely via a `softfloat` namespace or such)
=> [3.1] remove broad 'using namespace boost' causing float128_t conflict; fixes builds w/ boost 1.80

libraries/chain/include/eosio/chain/webassembly/interface.hpp
https://github.com/eosnetworkfoundation/mandel/issues/716
=> Wrong description for lowerbound comments 

libraries/chain/webassembly/crypto.cpp, unittests/crypto_primitives_tests.cpp
Based on benchmarking (see fc changes for details) and a desire to prevent deadline overruns longer than 5 ms (to protect timely block delivery), we decided to enforce a subjective limit of at most 2048 bits on any of the base, exponent, or modulus.
This can be adjusted in the future (higher or lower) without a consensus change since it is a subjective limitation. In the future, we may wish to solve the above concern in a more flexible way as described in https://github.com/eosnetworkfoundation/mandel/issues/738.
This PR also adds a test case to test that the subjective limit is enforced.
=> [3.1] Add subjective limit to mod_exp host function

libraries/chain/webassembly/crypto.cpp, unittests/crypto_primitives_tests.cpp
Brings #739 to main.
Resolves #361.
=> [3.1 -> main] Add subjective limit to mod_exp host function

libraries/chain/block_log.cpp, libraries/state_history/include/eosio/state_history/log.hpp
Resolves #714. Log message when enabling pruning will now be at info level, continual logging messages that are rather spammy will be at debug level instead.
=> [3.1] set prune logs at debug level except for the initial log when enabling pruning

libraries/chain/block_log.cpp, libraries/state_history/include/eosio/state_history/log.hpp
main port of 3.1's #718
> Resolves https://github.com/eosnetworkfoundation/mandel/issues/714. Log message when enabling pruning will now be at info level, continual logging messages that are rather spammy will be at debug level instead.
=> [3.1 -> main] set prune logs at debug level except for the initial log when enabling pruning

libraries/chain/webassembly/crypto.cpp, unittests/crypto_primitives_tests.cpp
A new approach to constraining the bit sizes of the arguments passed into mod_exp is taken which allows for larger bit sizes for the base and modulus arguments when the exponent is small.
This now allows for mod_exp to be used for 4096-bit RSA.
=> [3.1] Use more flexible subjective limits on mod_exp.

tests/CMakeLists.txt, tests/cli_test.py
Replace the cleos local ABI file test with a version implemented using the test harness and actually execute it.  The previous version was never executed by the test file.
=> Replace cleos local abi file test with test harness version.

libraries/chain/webassembly/crypto.cpp, unittests/crypto_primitives_tests.cpp
Brings #749 into main.
Resolves #747.
=> [3.1 -> main] Use more flexible subjective limits on mod_exp

plugins/net_plugin/net_plugin.cpp
Attempt a re-connect for duplicate connections so that any registered duplicate connections have an opportunity to re-establish a connection for the corner case of one side disconnecting as a duplicate simply because it had not yet closed its end of the connection. The re-connect will happen during the normal re-connect interval configured by `connection-cleanup-period`.
Resolves #755
=> [3.1] Attempt connection retries for duplicate connections

plugins/net_plugin/net_plugin.cpp
Attempt a re-connect for duplicate connections so that any registered duplicate connections have an opportunity to re-establish a connection for the corner case of one side disconnecting as a duplicate simply because it had not yet closed its end of the connection. The re-connect will happen during the normal re-connect interval configured by connection-cleanup-period.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/755
=> [3.1 -> main] Attempt connection retries for duplicate connections

plugins/resource_monitor_plugin/test/test_threshold.cpp, unittests/eosio.token_tests.cpp, unittests/state_history_tests.cpp
Most of these are to fix `comparison of integer expressions of different signedness` by replacing `int` with `size_t` for comparison against `vector<>::size()` unless otherwise noted
=> [3.2] grab bag of warning fixes

plugins/net_plugin/net_plugin.cpp
In the case the full block log is not available, prevent handshake message being sent sync-fetch count times to peer. For example, if the client requested 1000 blocks not available by the node, `net_plugin` would respond with 1000 handshake messages. Disconnect from peer with `benign_other` so the peer will move on to a different peer to sync from. This is what we already do for `blk_send_branch` when a block is not available.
Resolves #790
=> [3.1] Reduce net_plugin handshake messages in case of unavailable blocks

plugins/net_plugin/net_plugin.cpp
In the case the full block log is not available, prevent handshake message being sent sync-fetch count times to peer. For example, if the client requested 1000 blocks not available by the node, `net_plugin` would respond with 1000 handshake messages. Disconnect from peer with `benign_other` so the peer will move on to a different peer to sync from. This is what we already do for `blk_send_branch` when a block is not available.
Resolves #790
=> [3.1 -> main] Reduce net_plugin handshake messages in case of unavailable blocks

libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/transaction_context.cpp
Decision was made not to change exception, just a message, in particular:
Functions affected: validate_account_cpu_usage, validate_account_cpu_usage_estimate and checktime()
It is suggested that error messages with the condition of subjective_billed_us > 0 should be amended with following string:
" with a subjective cpu of (${subjective} us)"
for example, in validate_account_cpu_usage message should be updated as following:
Old:
"estimated CPU time (${billed} us) is not less than the maximum billable CPU time for the transaction (${billable} us)"
New:
"estimated CPU time (${billed} us) is not less than the maximum billable CPU time for the transaction (${billable} us) with a subjective cpu of (${subjective} us)"
Provisions has been made to avoid unneeded duplication of messages in a code.
=> [3.2] Enhancement: Add unique error message for subjective billing in the transaction trace logs

libraries/chain/include/eosio/chain/kv_config.hpp
As per the discussion on https://github.com/eosnetworkfoundation/mandel/issues/763, the comment in the header has been updated to indicate that it is not in use.  Removal of `kv_database_config` will cause snapshots to need to be updated, which is not desirable at this time. 
When some later change causes the need for v7 snapshots, that would be when the removal should occur.
=> [3.2] insert comments in the kv_config header file indicating it is not in use

plugins/chain_plugin/chain_plugin.cpp
Resolve https://github.com/eosnetworkfoundation/mandel/issues/800.
=> [3.1] Increase default transaction-retry-max-expiration-sec from 90 to 120

plugins/chain_plugin/chain_plugin.cpp, scripts/install_deps.sh
Merge 3.1 PR https://github.com/eosnetworkfoundation/mandel/pull/809 to main (resolving Resolve https://github.com/eosnetworkfoundation/mandel/issues/800.). The merge also gets changes from https://github.com/eosnetworkfoundation/mandel/pull/807.
=> [3.1 -> main] Increase default transaction-retry-max-expiration-sec from 90 to 120. Added file package to the list of installable packages.

tests/performance_tests/performance_test_basic.py, tests/trx_generator/main.cpp, tests/trx_generator/trx_provider.cpp
Working to connect the `performance_test_basic.py` to the `trx_generator` as well as make use of the `trx_provider` interface provided.
Update message in context free action of the transaction to be easier to parse in the future by delimiting with `:` and adding the current timestamp for future latency calculations.
Added command line arguments:
- `priv-keys` - comma-separated list of private keys in same order of accounts list that will be used to sign transactions. Minimum required: 2.
- `last-irreversible-block-id` - Current last-irreversible-block-id (LIB ID) to use for transactions.
Cleanup currently unused code/ideas like batching and previous implementations of push transaction(s).
Implement initial use of `trx_provider` to send transactions to the p2p interface.  Currently will …
=> Perf harness parts integration

tests/performance_tests/performance_test_basic.py, tests/trx_generator/main.cpp
Add cli params for configuring test transaction duration (sec) and target generation transactions per second (tps).
=> Configurable test duration and tps

docs/00_install/01_build-from-source/00_build-unsupported-os.md, docs/00_install/01_build-from-source/index.md, docs/01_nodeos/02_usage/03_development-environment/index.md, docs/01_nodeos/03_plugins/history_api_plugin/index.md, docs/01_nodeos/03_plugins/net_api_plugin/index.md, docs/01_nodeos/03_plugins/net_plugin/index.md, docs/01_nodeos/03_plugins/state_history_plugin/10_how-to-fast-start-without-old-history.md, docs/01_nodeos/03_plugins/state_history_plugin/40_how-to-restore-snapshot-with-full-history.md, docs/01_nodeos/07_concepts/05_storage-and-read-modes.md, docs/01_nodeos/08_troubleshooting/index.md, docs/02_cleos/02_how-to-guides/how-to-create-a-wallet.md, docs/02_cleos/02_how-to-guides/how-to-create-an-account.md, docs/02_cleos/02_how-to-guides/how-to-delegate-CPU-resource.md, docs/02_cleos/02_how-to-guides/how-to-delegate-net-resource.md, docs/02_cleos/02_how-to-guides/how-to-get-account-information.md, docs/02_cleos/02_how-to-guides/how-to-get-block-information.md, docs/02_cleos/02_how-to-guides/how-to-get-transaction-information.md, docs/02_cleos/02_how-to-guides/how-to-import-a-key.md, docs/02_cleos/02_how-to-guides/how-to-list-all-key-pairs.md, docs/02_cleos/03_command-reference/get/account.md, docs/02_cleos/03_command-reference/net/peers.md, docs/02_cleos/03_command-reference/net/status.md, docs/02_cleos/03_command-reference/set/set-account.md, docs/02_cleos/03_command-reference/set/set-action.md, docs/index.md, tutorials/bios-boot-tutorial/README.md
**Summary**
* Support MDX parsing
* Replace github references to EOS Network Foundation
* Replace references to old documentation portal
* Fix broken links
**Impacted files**: markdown files under `docs` and under `tutorial`
<hr/>
The developer documentation portal is powered by markdown files. These files are parsed to create a nice looking web site. We use MDX as the parsing engine. MDX requires all html tags are closed. We went through all the files removing unneeded &lt;hr&gt; tags, enclosing angle brackets in quotes, and closing img tags.
Many times we found documentation pointing to old repositories that had not been updated in years. We updated the links and pointed to repositories that are better maintained.
We made sure links to the documentation portal did not leak back to …
=> documentation fixes to power developer doc portal
