.cicd/test.sh, plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, tests/CMakeLists.txt, tests/p2p_high_latency_test.py
Getting feature/oci_api_phase1 up to date with main HEAD
=> Merging latest main commits into feature branch

CMakeLists.txt, libraries/chain/include/eosio/chain/deep_mind.hpp, plugins/chain_plugin/test/test_account_query_db.cpp, programs/eosio-launcher/main.cpp, unittests/misc_tests.cpp
- Fix some annoying warnings including linker warning on mac.
=> Fix warnings

docs/01_nodeos/03_plugins/chain_plugin/index.md, docs/01_nodeos/03_plugins/net_plugin/index.md, docs/01_nodeos/03_plugins/producer_plugin/index.md, docs/02_cleos/03_command-reference/push/push-action.md, docs/02_cleos/03_command-reference/push/push-transaction.md, programs/cleos/main.cpp
- Also updated for missing options not in the docs.
=> Add docs for transaction retry

tests/nodeos_high_transaction_test.py, tests/nodeos_retry_transaction_test.py
- Wait for trx so transfer does not fail because the account does not exist yet.
=> Improve integration test stability

unittests/CMakeLists.txt, unittests/gen_protocol_feature_digest_tests.py
=> Add unit test to verify that the description digests of protocol features are correct

libraries/chain/include/eosio/chain/chain_id_type.hpp
=> Remove unused code

unittests/api_tests.cpp
=> Add tests for multi_index iterator cache across notifies

docs/02_cleos/03_command-reference/get/block.md, libraries/chain/include/eosio/chain/exceptions.hpp, plugins/chain_api_plugin/chain.swagger.yaml, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, programs/cleos/httpc.hpp, programs/cleos/main.cpp
- Resolves: https://github.com/eosnetworkfoundation/mandel/issues/32
- Backports: https://github.com/EOSIO/eos/pull/8704
& https://github.com/EOSIO/eos/pull/9557
```
./cleos get block --info 5
{
"block_num": 5,
"ref_block_num": 5,
"id": "00000005eff86b22bce328d357fe77de1bc8fb3319f871ac33d6fd90ca842967",
"timestamp": "2022-05-05T02:20:42.000",
"producer": "eosio",
"confirmed": 0,
"previous": "00000004b68d6e41aa6f77e4ebfd3d6c48787f22203d2be881b5a256caf7dcae",
"transaction_mroot": "0000000000000000000000000000000000000000000000000000000000000000",
"action_mroot": "42b17e9ddf2a9f5aa64d0388965d923f2e80a692afc28038d339ff84bce9e436",
"schedule_version": 0,
"producer_signature": "SIG_K1_KcngsRWvntLXbWvZoVVEFujPcLAzzhUFd91QbrRw9ZNNtoTAv3RHuzjGw28MbiNWNwyqYKdp31dJKqDx6gfdcWwNEnnf2G", …
```
=> Add RPC /v1/chain/get_block_info

programs/cleos/main.cpp
=> Fix spelling error in cleos #178

libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm.hpp, libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp, libraries/chain/webassembly/runtimes/eos-vm.cpp
More unused wasm injection stuff here (all runtimes return false to this query)
=> remove more unused wasm injection code

libraries/chain/include/eosio/chain/webassembly/common.hpp
Backport https://github.com/EOSIO/eos/pull/9368
Resolves https://github.com/eosnetworkfoundation/mandel/issues/241
=> Remove unnecessary strlen

tests/CMakeLists.txt
=> remove left over unused and unneeded nodejs search in cmake file

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
get_info now returns earliest available block and additionally the time for the last irreversible block.
resolves https://github.com/eosnetworkfoundation/mandel/issues/118
example output:
`{"server_version":"44aa8277","chain_id":"967f7fc2d25df600681b8749e92914ae33814b5b02b98e9e130ea1aff5bc292d","head_block_num":576,"last_irreversible_block_num":334,"last_irreversible_block_id":"0000014ea2ea8adbfa4ac1da749a6d229bf481f9d6eb9cb3a27578ae6da5a421","head_block_id":"00000240d1921b9e77d1dbc1a679c62456139853b9a3910b20a97f1b3e80626e","head_block_time":"2022-05-19T21:55:54.500","head_block_producer":"defproducere","virtual_block_cpu_limit":284137889,"virtual_block_net_limit":1863613,"block_cpu_limit":159999900,"block_net_limit":1048576,"server_version_string":"v3.1.0-dev","fork_db_head_block_num":576 …
=> Added earliest available block to get_info 

tests/nodeos_forked_chain_test.py
nodeos_forked_chain_test.py
Resolves https://github.com/eosnetworkfoundation/mandel/issues/286
=> Fix test error log statement and import

plugins/resource_monitor_plugin/test/test_resmon_plugin.cpp
needed this with gcc12 and `std::this_thread::sleep_for()`
=> add needed <thread> include

tests/Node.py
=> Fix plugin http api test [main]

scripts/install_deps.sh, scripts/pinned_build.sh
main merge of 3.1's #532 resolving a number of issues with pinned build script
=> [3.2] misc pinned build script fixes

CONTRIBUTING.md
`s/eos/mandel/g` but also fix up of branch names & links
=> [3.1] fixup CONTRIBUTING.md

README.md
=> [3.1 -> main] Pull in 3.1.0-rc2

libraries/state_history/create_deltas.cpp, unittests/state_history_tests.cpp
Resolves: https://github.com/eosnetworkfoundation/mandel/issues/598
=> [3.2] Backport: pop a delta with empty rows

tests/chain_plugin_tests.cpp, tests/plugin_http_api_test.py
> Add integration test cases for get_consensus_parameters RPC endpoint.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/455
=> [3.2] Add test cases for get_consensus_parameters RPC endpoint 

tests/chain_plugin_tests.cpp, tests/plugin_http_api_test.py
> Add integration test cases for get_consensus_parameters RPC endpoint.
Resolves https://github.com/eosnetworkfoundation/mandel/issues/455
=> [3.2] Add test cases for get_consensus_parameters RPC endpoint

tests/CMakeLists.txt, tests/txn_generator/CMakeLists.txt, tests/txn_generator/main.cpp
Very rough first draft of a transaction generator to lay the basis for development. Much of this will be refactored or removed as responsibility is delegated to other pieces of the perf harness.  As well as adding command line options as much is hard coded at this time.
=> Transaction Generator - Initial commit.

scripts/install_deps.sh
Added "file" package to list of installable packages
=> [3.1] Added file package to the list of installable packages

tests/trx_generator/trx_provider.cpp, tests/trx_generator/trx_provider.hpp
Changed to code to not use net plugin code except the buffer building for the transaction provider.
=> Moved to using a sync socket implementation

docs/00_install/01_build-from-source/00_build-unsupported-os.md, docs/00_install/01_build-from-source/index.md, docs/01_nodeos/02_usage/03_development-environment/index.md, docs/01_nodeos/03_plugins/history_api_plugin/index.md, docs/01_nodeos/03_plugins/net_api_plugin/index.md, docs/01_nodeos/03_plugins/net_plugin/index.md, docs/01_nodeos/03_plugins/state_history_plugin/10_how-to-fast-start-without-old-history.md, docs/01_nodeos/03_plugins/state_history_plugin/40_how-to-restore-snapshot-with-full-history.md, docs/01_nodeos/07_concepts/05_storage-and-read-modes.md, docs/01_nodeos/08_troubleshooting/index.md, docs/02_cleos/02_how-to-guides/how-to-create-a-wallet.md, docs/02_cleos/02_how-to-guides/how-to-create-an-account.md, docs/02_cleos/02_how-to-guides/how-to-delegate-CPU-resource.md, docs/02_cleos/02_how-to-guides/how-to-delegate-net-resource.md, docs/02_cleos/02_how-to-guides/how-to-get-account-information.md, docs/02_cleos/02_how-to-guides/how-to-get-block-information.md, docs/02_cleos/02_how-to-guides/how-to-get-transaction-information.md, docs/02_cleos/02_how-to-guides/how-to-import-a-key.md, docs/02_cleos/02_how-to-guides/how-to-list-all-key-pairs.md, docs/02_cleos/03_command-reference/get/account.md, docs/02_cleos/03_command-reference/net/peers.md, docs/02_cleos/03_command-reference/net/status.md, docs/02_cleos/03_command-reference/set/set-account.md, docs/02_cleos/03_command-reference/set/set-action.md, docs/index.md, tutorials/bios-boot-tutorial/README.md
Reverts eosnetworkfoundation/mandel#748
=> Revert "documentation fixes to power developer doc portal"
